name: Test Scripts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        account: [personal-jeffrey, work-uaa, business-happy-patterns, personal-ahniel]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: '10.14.0'
        run_install: false
    
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Check pnpm version
      run: pnpm run check:pnpm || true
    
    - name: Run shared library tests
      run: |
        if [ -d "tests/unit" ]; then
          pnpm test -- tests/unit
        fi
    
    - name: Validate account configuration
      run: |
        node -e "
        const fs = require('fs');
        const config = JSON.parse(fs.readFileSync('accounts/${{ matrix.account }}/account.json'));
        console.log('Valid config for:', config.account.email);
        "
    
    - name: Check script syntax
      run: |
        for script in accounts/${{ matrix.account }}/scripts/*/; do
          if [ -d "$script" ]; then
            echo "Checking: $script"
            find "$script" -name "*.js" -o -name "*.gs" | xargs -I {} node -c {}
          fi
        done